# Generated by Django 4.1.5 on 2023-04-25 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receipe",
            old_name="description",
            new_name="receipe_description",
        ),
        migrations.RenameField(
            model_name="receipe",
            old_name="image",
            new_name="receipe_image",
        ),
        migrations.RenameField(
            model_name="receipe",
            old_name="name",
            new_name="receipe_name",
        ),
    ]
